version: '3.1'
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind

services:
  db:
    container_name: mariadb
    build: requirements/MariaDB
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - Inception
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: on-failure
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/Nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - Inception
    env_file:
      - .env
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    depends_on:
      - db
    build: requirements/WordPress
    volumes:
      - wordpress:/var/www/html
    networks:
      - Inception
    env_file:
      - .env
    ports:
      - "9000:9000"
    restart: on-failure
networks:
  Inception:
