version: '3.1'
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /Users/m4rrs/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/m4rrs/data/wordpress
      o: bind

services:
  db:
    container_name: mariadb
    build: requirements/MariaDB
    networks:
      - Inception
    env_file:
      - .env
    ports:
      - 3306:3306
    restart: on-failure
  nginx:
    container_name: nginx
    build: requirements/Nginx
    networks:
      - Inception
    env_file:
      - .env
    ports:
      - 443:443
    restart: on-failure
  wordpress:
    container_name: wordpress
    depends_on:
      - db
    build: requirements/WordPress
    networks:
      - Inception
    env_file:
      - .env
    ports:
      - 9000:9000
    restart: on-failure
networks:
  Inception:
